### ISSUE TITLE
No Instructions

### ISSUE THREAD

**Issue by conetopia** [squeek502/d2itemreader#10]
No idea how to install or Build .exe

**Comment by squeek502** [comment]
There is no `.exe` to output, this is primarily a library to be used by others. There is some example code of basic `.exe`s [here](https://github.com/squeek502/d2itemreader/tree/master/examples), though.

To build, you need [CMake](https://cmake.org/). CMake will then generate the Visual Studio solution files you (if you're on Windows). [Here's one guide](https://cmake.org/runningcmake/).

You can also use the [`make.bat`](https://github.com/squeek502/d2itemreader/blob/master/make.bat) provided in the repository, although it might be a bit out-of-date at this point.
