### ISSUE TITLE
Corrupted .sss file please help

### ISSUE THREAD

**Issue by harry-hathorn** [squeek502/d2itemreader#7]
Hi @squeek502 

Please could you help me. I couldn't find another way to contact you so i'm opening an issue.

I'm looking for a way of restoring my plugy shared stash file. It got corrupted when plugy didnt save properly.

I'm trying to read my .sss file and see if i can restore it. Is this possible? Do you know how I could do it?

I'm busy looking at the plugy source code and found your repo which looks promising on how to read a .sss file. 

When i try to use the corrupted .sss file the game gives error 9 "Unable to enter game. Bad header" 

When I only try to use the bad character i get "Unable to enter game. Bad character version"

Please find the attached .sss file. I haven't figured out how to use the d2itemreader yet. 
[save_files.ZIP](https://github.com/squeek502/d2itemreader/files/3998896/save_files.ZIP)

// Harry

**Comment by squeek502** [comment]
Sadly, your shared stash (.sss) and your character's personal stash (.d2x) are unrecoverable; the files are nothing but zeroes all the way through:

![sss](https://user-images.githubusercontent.com/2389051/71426078-72e86880-2659-11ea-9dbe-fc3e2443c793.png)

Not sure how that happened, but that's a really bad bug if it's something that PlugY did to itself. :disappointed: 

Your .d2s seems fine, though, so it might be the .d2x file that is causing your character to fail loading. If you remove your .sss and .d2x (or rename them) then you should be able to load your character again.

**Comment by squeek502** [comment]
Closing as resolved. Let me know if you have any more questions.
